---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: adguard-credentials
  namespace: adguard
spec:
  encryptedData:
    password: AgCROaDsidxDrkQNrXEeTWZrJt0NO5D4ciMODqppMVFQ1YGebGK36wDG48knrThft6mK/TbjUmaGwmFq0XMAR9yemUg8erZNTPiXWBjKx2rSqxCND92LhluF/7yg+Ypo5JE68RVMECcpfEH0+MPhqww7lAiueVbuDLnRihzvMoqZPp4CBfh2UIRJm5BlFPjVtR/iMr13J8wQJk5LUnVLisSUuvfF0zuTmJ3s6hC08eFniR/4ZyCuXujf8Utp+q6Zri9Nxw0M1dnS8kt0a7MOyG4FgntWtTBEY9j84T2Spqr7VGUC/ok1ayx4uM/H08hYOAnDn+NRSLu8kgw6eMZZH2PVAzYgeU/RY3z+nZYhdLWF2TbcOAB0QTF4Rh1fm/XtD2ZGfTBQ0tk6ehX9NN//5y3KKNEsEdRhaxTtCt3LfPQTZC1Ue0XY94Klm2qPxtnfL/0rSgRyNHT/XqZOIob871Sw7LneoSPM5303koaHr0zUtiXgYgaukTfXhMhMdSCkSxyd6mSphUazDFar/CSwRXhGqcsoCOEFBZswxT8e2smxFkqqqfsk7Eu+st/IHQIJMqWyDI10F1qRUMuHxOsEeLE11b2OSrzUSQOMaQ+Q5wCXspidNUw6Gwx23SDmfL0TsIEUJTiCytk9ulEeUdXpkSFkQpWzGd8jIH2bKOSoZQ00KGPBXaPoJ/lNSel6veHJRPt8CP2iKpFmUYdxXkdkYKtY9nbcae4Y6nj+1Umcbs3b+eWILffq5Pg8ztTrOIfs9EF8/LBZT0/X4ZT+ydI=
    username: AgAuzgCVyn3fdhH6V8BvUmViX4i60Qh9hx3BLzMzleAkI3vZBIrQEJ9LhzfCI/I2vr4D12tXvCZGnjjhk6EsDHMIMGfRjIkzheCHa5N4BzxeVR1pYNw07S1v6qscdNsmNRasllSTi5P5MUDmbp5iiGCSsfkAHusUpDzjmW9WjfIeJNh4vVma4tLUWBn/pMf+rqy2eZb18Dq5kV+OhYi+fkgSYHDungWIp6tXNK/k0jqzb+yvOJemaY/9oCLdRV08HNSyCZT1YGEx5sqwbvPavu3cBfgOqeBJCanEuf4rvPyv7eZCuNdl3S5XefvDyNaEDbw4GNqJG4lN3TbzYEjrIBBd25/5bwaNjp+lp30ytfewzxKYKkbXJxvtEleLiLHy30dG9P3I4dfOO2pGTzBOLNx+VN7vofDaUWys/Lndr05SgFz6hOdf0zjvd03QpmJxHOiixn7DOQLg2N9qv7Ri49/2bWyHJPsqedj/7D4fMcEMi78NU1LSsQNZnYeloMoYJQxR/OrlSvrY0dTjy3qbNp+3ESPajAT2QLlJVC3DEm5byWMWQI1+UOfWtsUiVGlr4pe1Zj4EKV4GfDWDikov7uKMm4j6t/HnCPW5Z9BWZRbfpxtFcjVY3wNZOkcFxGxz3aLyS3TsVRWRnEMLtC2294BsrDHIskH4H8eVvQQgQl/yhu3QjRiV+7xhQd9kmcGJZDgfOqbmhg==
  template:
    metadata:
      name: adguard-credentials
      namespace: adguard
