apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: beszel-agent
spec:
  selector:
    matchLabels:
      app: beszel-agent
  template:
    metadata:
      labels:
        app: beszel-agent
    spec:
      hostNetwork: true
      containers:
        - env:
            - name: HUB_URL
              value: "http://192.168.0.123:8090"
            - name: LISTEN
              value: "45876"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  key: TOKEN
                  name: bezel-creds
            - name: KEY
              valueFrom:
                secretKeyRef:
                  key: KEY
                  name: bezel-creds
          image: henrygd/beszel-agent:latest
          imagePullPolicy: Always
          name: beszel-agent
          ports:
            - containerPort: 45876
              hostPort: 45876
          volumeMounts:
            - mountPath: /beszel_agent_data
              name: beszel-agent-data
      restartPolicy: Always
      volumes:
        - name: beszel-agent-data
          hostPath:
            path: /var/lib/beszel-agent
            type: DirectoryOrCreate
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 100%
    type: RollingUpdate