---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance-agent
  labels:
    app.kubernetes.io/name: glance-agent
    app.kubernetes.io/instance: glance-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: glance-agent
      app.kubernetes.io/instance: glance-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glance-agent
        app.kubernetes.io/instance: glance-agent
    spec:
      nodeSelector:
        k8s.imkavin.dev/nodepool: workers
      containers:
        - name: glance-agent
          image: glanceapp/agent
          ports:
            - containerPort: 27973
---
apiVersion: v1
kind: Service
metadata:
  name: glance-agent
  labels:
    app.kubernetes.io/name: glance-agent
    app.kubernetes.io/instance: glance-agent
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: glance-agent
    app.kubernetes.io/instance: glance-agent
  ports:
    - port: 27973
      targetPort: 27973
      protocol: TCP