---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bws-access-token
  namespace: external-secrets
spec:
  encryptedData:
    ACCESS_TOKEN: AgCYdtYPLnxI1DVoDQvR4+uKhnVG3x9irD8OU/HuN/g6Lz41wcZ1VIa4juzww7xpiiLeYul2gIPbaP8Eij+nJ19sjdf0RA0ABhr8g9Z30a1nsdUrk4d4qBbZvxh+govX3Pry9Febcvzwi+u29tiwg2k6D1bZ8KKlkIgynfcrzi6+71ca5oTvaoLKcgI6D+8G2N1WRewheKNbM+7GtkeGQQ7bhDc+J6nlBiR9RAEADq8h0O4vdQo+Zz25IOCkd3Nj8Unc60ByEkRjFLJmmRGgViJf2z1EGIt0N5j3J3ht+B4Sn+MeBTojB+etAjhrA6L6R+W0/HkLrq2+kYKitU+bTtML+DwcuKFSL/mm5LFyfru2DF0rLkuP4Xlq5s0GFXO8be3Jf2S2sYALecl3fWLCBpDJ4Em2wrDd4c2o0zoiPEg7M7KWf/NonRGcBrekN9z+QYu+d3Oem7WXm2ewS/+UuuXOeA6ouDd5a17/GDhYLQbZQt2WWK+yEQW9FNpKdjLtfXhGmif0KoQwjTWQZXTDPwL5TpyF7Z5oSY8In0OUrlkq6juKwxsLc8eiMSwYNgVQmULjcXdmMQtUuDtsBzbDc88pa8TegeoQWJw0AWdVUdPnIN5/kHznPt8hcPykxpJPoj3hi/6J4Lrej2IKjZIkSjjenh1/nlJfTGPDAVfh0587amIxjALRkFJZ2u3wFogipDe02prgKDXTsI0/jtY6lK+LhkzOeQrSIEySrch/j4A8oAoia1Wyzc+SKA/5AXoXtfkhr1mJ5z+EJjxWyKOjXDgCbj2pLbet4ErTc75xJOwC6Uz4KifiAdmWZCa71hMS
  template:
    metadata:
      name: bws-access-token
      namespace: external-secrets
